# Generated by Django 5.1.6 on 2025-02-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensesplit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpenseSplit',
        ),
    ]
