# Generated by Django 5.1.6 on 2025-02-20 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expense_group_id_expense_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
