
# Generated by Django 5.1.6 on 2025-02-20 13:38


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_expensesplit_created_at"),
        ("group", "0002_alter_groupmember_user"),


    operations = [
        migrations.AlterField(

            model_name="expense",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="group.group",
            ),

        ),
    ]
