# Generated by Django 5.1.6 on 2025-02-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_group'),
    ]

    operations = [
    ]
