# Generated by Django 5.1.6 on 2025-02-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0008_alter_expense_amount_alter_expensesplit_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="title",
            field=models.CharField(default="no title", null=True),
        ),
    ]
